---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
  labels:
    stackable.tech/vendor: Stackable
spec:
  image:
    productVersion: 3.0.1
  clusterConfig:
    listenerClass: external-unstable
    credentialsSecret: superset-credentials
    mapboxSecret: superset-mapbox-api-key
  nodes:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-credentials
  labels:
    stackable.tech/vendor: Stackable
type: Opaque
stringData:
  adminUser.username: admin
  adminUser.firstname: Superset
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: {{ supersetAdminPassword }}
  connections.secretKey: {{ supersetSecretKey }}
  connections.sqlalchemyDatabaseUri: postgresql://superset:superset@postgresql-superset/superset
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-mapbox-api-key
  labels:
    stackable.tech/vendor: Stackable
type: Opaque
stringData:
  connections.mapboxApiKey: "pk.eyJ1IjoibXVlbGxlcmNlbGluZSIsImEiOiJjbDZwM3llMTAwNGpmM2psdHU0Y21wZHJwIn0.kXFJKBbeyhbwf0z460JcTQ"
---
apiVersion: superset.stackable.tech/v1alpha1
kind: DruidConnection
metadata:
  name: superset-druid-connection
  labels:
    stackable.tech/vendor: Stackable
spec:
  superset:
    name: superset
  druid:
    name: druid
