---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-iceberg
spec:
  image:
    # Cannot upgrade to 4.0.1 because we run into github.com/apache/iceberg/issues/12878
    productVersion: 4.0.0
  clusterConfig:
    authorization:
      opa:
        configMapName: opa
        package: hive_iceberg
    metadataDatabase:
      postgresql:
        host: postgresql-hive-iceberg
        database: hive
        credentialsSecretName: hive-postgres-credentials
    hdfs:
      configMap: hdfs
    authentication:
      kerberos:
        secretClass: kerberos
  metastore:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: hive-postgres-credentials
type: Opaque
stringData:
  username: hive
  password: hive
