---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-iceberg
spec:
  image:
     # Cannot upgrade to 4.0.1 because we run into the same problem
     # as this https://github.com/apache/iceberg-python/issues/1222
    productVersion: 4.0.0
  clusterConfig:
    authorization:
      opa:
        configMapName: opa
        package: hive_iceberg
    database:
      connString: jdbc:postgresql://postgresql-hive-iceberg:5432/hive
      credentialsSecret: postgres-credentials
      dbType: postgres
    hdfs:
      configMap: hdfs
    authentication:
      kerberos:
        secretClass: kerberos
  metastore:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
stringData:
  username: hive
  password: hive
