---
# {% raw %}
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-metastore-regorules
  labels:
    opa.stackable.tech/bundle: "true"
data:
  actual_permissions.rego: |
    package hive_iceberg

    trino_user := "trino"
    spark_user := "spark"
    customer_analytics_db := "customer_analytics"
    compliance_analytics_db := "compliance_analytics"

    default database_allow = false
    default table_allow = false
    default column_allow = false
    default partition_allow = false
    default user_allow = false

    ### SPARK ###
    # These rules are tailored for the create-spark-report job.

    # Allow the spark user access to the 'customer_analytics_db'
    database_allow if {
      input.identity.username == spark_user
      input.resources.database.name == customer_analytics_db
    }

    # Allow the 'SELECT * FROM lakehouse.customer_analytics.customer' query in create-spark-report
    table_allow if {
      input.identity.username == spark_user
      input.resources.table.dbName == customer_analytics_db
      input.resources.table.tableName == "customer"
      input.privileges.readRequiredPriv[0].priv == "SELECT"
    }

    # Allow the 'CREATE TABLE IF NOT EXISTS lakehouse.customer_analytics.spark_report AS SELECT c_birth_country, count(*) FROM ..'
    # query in create-spark-report
    table_allow if {
      input.identity.username == spark_user
      input.resources.table.dbName == customer_analytics_db
      input.resources.table.tableName == "spark_report"
      input.privileges.writeRequiredPriv[0].priv == "CREATE"
    }

    ### TRINO ###
    # We allow everything here for the technical trino user in order to still do data exploration
    database_allow if {
      input.identity.username == trino_user
    }

    table_allow if {
      input.identity.username == trino_user
    }

    column_allow if {
      input.identity.username == trino_user
    }

    partition_allow if {
      input.identity.username == trino_user
    }

    user_allow if {
      input.identity.username == trino_user
    }

# {% endraw %}
