---
apiVersion: opa.stackable.tech/v1alpha1
kind: OpaCluster
metadata:
  name: opa
spec:
  image:
    productVersion: 1.16.2
    pullPolicy: IfNotPresent # TODO: Temp to be able to use make run-dev in opa-operator
  clusterConfig:
    userInfo:
      backend:
        keycloak:
          hostname: keycloak.{{ NAMESPACE }}.svc.cluster.local
          port: 8443
          tls:
            verification:
              server:
                caCert:
                  secretClass: tls
          clientCredentialsSecret: user-info-fetcher-client-credentials
          adminRealm: demo
          userRealm: demo
    resourceInfo:
      backend:
        dataHub:
          hostname: datahub-datahub-gms.{{ NAMESPACE }}.svc.cluster.local
          port: 8080
          clientCredentialsSecretName: resource-info-fetcher-client-credentials
          env: PROD
      cache:
        entryTimeToLive: 0s
  servers:
    config:
      logging:
        containers:
          opa:
            console:
              level: INFO
            file:
              level: INFO
            loggers:
              decision:
                level: INFO
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: resource-info-fetcher-client-credentials
stringData:
  clientId: __datahub_system
  clientSecret: datahub-demo-system-secret
