---
apiVersion: opa.stackable.tech/v1alpha1
kind: OpaCluster
metadata:
  name: opa
spec:
  image:
    productVersion: 0.67.1
  clusterConfig:
    userInfo:
      backend:
        keycloak:
          hostname: keycloak.default.svc.cluster.local
          port: 8443
          tls:
            verification:
              server:
                caCert:
                  secretClass: tls
          clientCredentialsSecret: user-info-fetcher-client-credentials
          adminRealm: demo
          userRealm: demo
  servers:
    config:
      logging:
        containers:
          opa:
            loggers:
              decision:
                level: INFO
    roleGroups:
      default:
        replicas: 1
