---
apiVersion: opa.stackable.tech/v1alpha1
kind: OpaCluster
metadata:
  name: opa
spec:
  image:
    productVersion: 0.61.0
  clusterConfig:
    userInfo:
      backend:
        {% if userInfoFetcherBackend == "keycloak" %}
        keycloak:
          clientCredentialsSecret: user-info-fetcher-client-credentials
          adminRealm: master
          userRealm: master
          hostname: keycloak
          tls:
            verification:
              none: {}
        {% elif userInfoFetcherBackend == "aas" %}
        experimentalXfscAas:
          hostname: aas
        {% endif %}
  servers:
    roleGroups:
      default:
        replicas: 1
