# Helper Rego rules for the UserInfoFetcher.
#
# Add rules like this for your product specific input:
#
# currentUserInfoByUsername := uif.userInfoByUsername(input.username)
# currentUserInfoById := uif.userInfoById(input.id)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uif-regorules
  labels:
    opa.stackable.tech/bundle: "true"
data:
  test.rego: |
    package uif

    userInfoByUsername(username) := http.send({"method": "POST", "url": "http://127.0.0.1:9476/user", "body": {"username": username}, "headers": {"Content-Type": "application/json"}, "raise_error": true}).body
    userInfoById(id) := http.send({"method": "POST", "url": "http://127.0.0.1:9476/user", "body": {"id": id}, "headers": {"Content-Type": "application/json"}, "raise_error": true}).body
