additionalLabels:
  stackable.tech/vendor: Stackable
podLabels:
  stackable.tech/vendor: Stackable
rootUser: admin
rootPassword: adminadmin
mode: standalone
persistence:
  size: 10Gi
buckets:
  - name: demo
    policy: public
resources:
  requests:
    cpu: 1
    memory: 2Gi
service:
  type: NodePort
  nodePort: null
consoleService:
  type: NodePort
  nodePort: null
extraVolumes:
  # Request a TLS certificate from the secret-operator
  - name: tls
    ephemeral:
      volumeClaimTemplate:
        metadata:
          annotations:
            secrets.stackable.tech/class: tls
            secrets.stackable.tech/scope: |-
              service=minio
        spec:
          storageClassName: secrets.stackable.tech
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1
  # Create an in-memory emptyDir to copy the certs to (to avoid permission errors)
  - name: certs
    emptyDir:
      sizeLimit: 5Mi
      medium: Memory
extraVolumeMounts:
  # Mount the certificate generated by the secret-operator
  - name: tls
    mountPath: /etc/minio/original_certs
  # On startup, we will rename the certs and move them here:
  - mountPath: /etc/minio/certs
    name: certs
