---
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: nifi
spec:
  image:
    productVersion: 2.2.0
    # TODO (@NickLarsenNZ): Use a versioned image with stackable0.0.0-dev or stackableXX.X.X so that
    # the demo is reproducable for the release and it will be automatically replaced for the release branch.
    custom: oci.stackable.tech/stackable/nifi:2.2.0-postgresql
    # pullPolicy: IfNotPresent
  clusterConfig:
    listenerClass: external-unstable
    zookeeperConfigMapName: nifi-znode
    authentication:
      - authenticationClass: nifi-users
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
  nodes:
    config:
      resources:
        cpu:
          min: "500m"
          max: "4"
        memory:
          limit: '6Gi'
        storage:
          contentRepo:
            capacity: "10Gi"
          databaseRepo:
            capacity: "1Gi"
          flowfileRepo:
            capacity: "2Gi"
          provenanceRepo:
            capacity: "4Gi"
          stateRepo:
            capacity: "1Gi"
    roleGroups:
      default:
        replicas: 1
---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: nifi-users
spec:
  provider:
    static:
      userCredentialsSecret:
        name: nifi-admin-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: nifi-admin-credentials
stringData:
  admin: {{ nifiAdminPassword }}
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: nifi-znode
spec:
  clusterRef:
    name: zookeeper
