---
version: 2

models:
  - name: my_table
    description: "A simple demo table with integer IDs"
    columns:
      - name: id
        description: "ID value"
        tests:
          - not_null        # built-in dbt test
          - unique          # optional: ensure no duplicates
          - id_in_range
