---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-postgresql-credentials
  namespace: stackable-airflow
spec:
  encryptedData:
    password: AgBc32xJVX5MxFZIBfJ7KsgGxLTJHCxPIVhXT3rYbLaPPojIDfu+8ygtdc3UqzFc//nuxbg8WkCUI6UclxGkL9ODUknvQTYCd8ZtmbGfI7BaSbZLhQe5qzd1LLnKtVil2xvYKidtPiob2nn76I8BfiAoenWl9cEqJT3aAYdbau5rMO+WTmc6Sl2+Dl2tBGQBajZRPOB2474NFpEVHf+wOZrIRZhslYBL4i905wkUrpp3G6EPWJRVbeqNFRBYpAxJhMJgny84wLN9xt25L+B6XMagNuo6jXfHBpYkEuyb07k1vJd+4ij1w9w31Lf7HEmsFuLeQnYszyohecCBosORsNI0jwcs4QPbaCerBBZiLftIjAZEOrlU1EoF3I/K3SKJXtxN8ofq0IvNksJ5O+Ofgudi+eOdrdiVHQcDfh6afn0o0bFyQ5CB+/BbeA+nmOlcj0A1xNf8OmBEu6ARA7YQs8vwUMqvfh5BTxv0nmH/OMQkpIVqx8Ik0n7bUoJZNh21uYFATnfONx6R0kvz/WcLSW6qVt8xlr08sKjJh8BQi8WTnXISzZDbTG/j2O2vCD5TGgQ/JFGKzii32KCXw5d4Uk02nAvJhkbM8Xm+A5kC5d1g/w1W0/lnU4nVlkyJPq81A5R3+Pk/8jh96/u0oKjiBaqrQA3Qmam0mMt1k0ITmtMZy583y+BTqtrcU1H9HRV87n05DIZ4Z1ug
    username: AgBmgNVPYGAsq2spiGiEqAHFqlww9hy8hFX9xhkJW3UWE+/DYzOCqfCIt+e5SMOD1sV+iTsbY/M7pRtGCafyq/pZPraQjs3tSYVC9ggUe/ApsQgWvVGnJJyENnBJAsyN/hH5PzQrgONFOS/B8Sdd4fYlngIEGkvZW/r5oXPmhiXfnUOKgT9f4E2GBVJPrmwZ4c2y34AxCv6Xf+qR7szNPOPYC4ELNPIGWUffOU0AYZHKXczz01fLbif5q/d8f7S6EbeU206xinGheEtsY6G2gDkP9cjgASJUqOq1Uq9tVvIlC1vU4fxo3v+D1pSDPbdHJj+shOtW26nUlNtmVbMCfMALnMbJ0Fowso6sCQY0Us+8FjuLoNHNUO+UFDMQgEVZuxCZGAVUoABAg05xdJCimmMgpvz632EslLcDtUJWpkpXcOzXFOgnrlr9vYHhm1catLUwrthOvV9xT+t6z1j00ztyxCYt9CEob5jNmtt/XEOWUl3iW0a6+Z/BHhwRN5/TjVi48n9WOWDGU66u7ZksDDv1eSgLumPFQUKjQVNUh9YgQdtUabATG6t2O5ttko6XGCTyZTBuCSoi/ZmVWrenF1gg8WoLCOFPk7UQvD8QlQsr/KEut2iZZUe4q3Hqp+KOwEnlXXZ10P+Da1Lr1StlA6FBdTy5YzTOmezkBI7nNwyM7udqB+/hmKDvpV9vA14JkZtjRGUUWn/I
  template:
    metadata:
      creationTimestamp: null
      name: airflow-postgresql-credentials
      namespace: stackable-airflow
      labels:
        stackable.tech/vendor: Stackable
        stackable.tech/demo: argo-cd-git-ops
    type: Opaque
