---
apiVersion: v1
kind: Secret
metadata:
  name: jupyterhub-client-credentials
stringData:
  clientId: jupyterhub
  clientSecret: jupyterhubjupyterhub #{{ keycloakJupyterhubClientSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-realm-config
stringData:
  # Created by clicking users in Keycloak WebUI and than running `/opt/keycloak/bin/kc.sh export --dir /tmp`
  # (as well as some manual modifications).
  realm.json: |
    {
      "realm" : "jupyterhub",
      "enabled" : true,
      "groups" : [],
      "users" : [],
      "clients" : [ {
        "clientId" : "jupyterhub",
        "enabled" : true,
        "protocol" : "openid-connect",
        "clientAuthenticatorType" : "client-secret",
        "secret" : "jupyterhubjupyterhub",
        "redirectUris" : [ "*" ],
        "webOrigins" : [ "*" ],
        "standardFlowEnabled" : true
      } ]
    }
