---
extends: default

rules:
  line-length: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1  # Needed due to https://github.com/adrienverge/yamllint/issues/443
  braces:
    # because the yaml files are templates which can have {{ ... }}
    ignore: |
      stacks/signal-processing/*
      stacks/_templates/*
