---
apiVersion: batch/v1
kind: Job
metadata:
  name: distcp-cycling-data
spec:
  template:
    spec:
      containers:
        - name: distcp-cycling-data
          # We use 24.3.0 here which contains the distcp MapReduce components
          # This is not included in the 24.7 and 24.11 images and will fail.
          # See: https://github.com/stackabletech/docker-images/issues/793
          image: oci.stackable.tech/sdp/hadoop:3.3.6-stackable24.3.0
          env:
            - name: HADOOP_USER_NAME
              value: stackable
            - name: HADOOP_CONF_DIR
              value: "/stackable/conf/hdfs"
            - name: HADOOP_CLASSPATH
              value: "/stackable/hadoop/share/hadoop/tools/lib/*.jar"
          # yamllint disable-line rule:line-length
          command:
            - bash
            - -euo
            - pipefail
            - -c
            - |
              bin/hdfs dfs -mkdir -p /data/raw
              bin/hadoop distcp -D fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider \
                s3a://public-backup-nyc-tlc/cycling-tripdata/demo-cycling-tripdata.csv.gz \
                hdfs://hdfs/data/raw
          volumeMounts:
            - name: config-volume-hdfs
              mountPath: /stackable/conf/hdfs
      volumes:
        - name: config-volume-hdfs
          configMap:
            name: hdfs
      restartPolicy: OnFailure
  backoffLimit: 50
