my_project:
  target: prod
  outputs:
    prod:
      type: trino
      method: ldap
      user: admin
      password: adminadmin
      host: trino-coordinator-default-headless.default.svc.cluster.local
      port: 8443
      database: iceberg
      schema: my_schema
      threads: 4
      http_scheme: https
      cert: /dbt/trusted/ca.crt
      session_properties:
        query_max_run_time: "4h"
        query_priority: 1
