# Find the latest python version here:
# https://quay.io/repository/jupyter/pyspark-notebook?tab=tags (use the tag search)
FROM quay.io/jupyter/pyspark-notebook:python-3.13

COPY demos/signal-processing/requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r ./requirements.txt
