# Find the latest python version here:
# https://quay.io/repository/jupyter/pyspark-notebook?tab=tags (use the tag search)
# NOTE: This can't run on Python 3.13 until https://github.com/SeldonIO/alibi-detect/issues/963 is resolved
FROM quay.io/jupyter/pyspark-notebook:python-3.12

COPY demos/signal-processing/requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r ./requirements.txt
