# docker build -f ./Dockerfile-nifi -t docker.stackable.tech/demos/nifi:1.25.0-postgresql .

FROM docker.stackable.tech/stackable/nifi:1.25.0-stackable0.0.0-dev

RUN curl --fail -o /stackable/nifi/postgresql-42.6.0.jar "https://repo.stackable.tech/repository/misc/postgresql-timescaledb/postgresql-42.6.0.jar"
