# Find the latest python version here:
# https://hub.docker.com/r/jupyter/pyspark-notebook/tags?name=python-
FROM jupyter/pyspark-notebook:python-3.11

COPY demos/signal-processing/requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r ./requirements.txt
