---
apiVersion: secrets.stackable.tech/v1alpha1
kind: TrustStore
metadata:
  name: truststore-pem
spec:
  secretClassName: tls
  format: tls-pem
  targetKind: ConfigMap
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: kafka
spec:
  image:
    productVersion: 4.1.0
  clusterConfig:
    tls:
      serverSecretClass: tls
  controllers:
    roleGroups:
      default:
        replicas: 1
  brokers:
    config:
      bootstrapListenerClass: cluster-internal
      brokerListenerClass: cluster-internal
    podOverrides:
        spec:
          containers:
            - name: kafka
              env:
              - name: BOOTSTRAP_SERVER
                valueFrom:
                  configMapKeyRef:
                    name: kafka
                    key: KAFKA
    roleGroups:
      default:
        replicas: 1
