apiVersion: opensearch.stackable.tech/v1alpha1
kind: OpenSearchCluster
metadata:
  name: opensearch
spec:
  image:
    productVersion: {{ opensearchVersion }}
    pullPolicy: IfNotPresent
  clusterConfig:
    security:
      settings:
        config:
          managedBy: API
          content:
            value:
              _meta:
                type: config
                config_version: 2
              config:
                dynamic:
                  authc:
                    basic_internal_auth_domain:
                      description: Authenticate via HTTP Basic against internal users database
                      http_enabled: true
                      transport_enabled: true
                      order: 1
                      http_authenticator:
                        type: basic
                        challenge: true
                      authentication_backend:
                        type: intern
                  authz: {}
                  kibana:
                    multitenancy_enabled: false
        internalUsers:
          managedBy: API
          content:
            valueFrom:
              secretKeyRef:
                name: opensearch-security-config
                key: internal_users.yml
        rolesMapping:
          managedBy: API
          content:
            value:
              _meta:
                type: rolesmapping
                config_version: 2
              all_access:
                reserved: false
                backend_roles:
                  - admin
              kibana_server:
                reserved: true
                users:
                  - kibanaserver
  nodes:
    roleGroups:
      default:
        config:
          listenerClass: cluster-internal
          resources:
            cpu:
              min: "1"
              max: "2"
            memory:
              limit: "2Gi"
            storage:
              data:
                capacity: 10Gi
        replicas: 1
    configOverrides:
      opensearch.yml:
        # Disable memory mapping; If enabled, the kernel setting vm.max_map_count
        # would need to be increased to 262144 on the node
        node.store.allow_mmap: "false"
        # Disable the disk allocation decider to prevent issues with security index creation
        cluster.routing.allocation.disk.threshold_enabled: "false"
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-security-config
stringData:
  internal_users.yml: |
    ---
    _meta:
      type: internalusers
      config_version: 2

    admin:
      hash: {{ bcrypt(password=openSearchAdminPassword) }}
      reserved: true
      backend_roles:
        - admin
      description: OpenSearch admin user

    kibanaserver:
      hash: {{ bcrypt(password=openSearchDashboardPassword) }}
      reserved: true
      description: OpenSearch Dashboards user
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-user
stringData:
  username: admin
  password: {{ openSearchAdminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-dashboard-user
stringData:
  username: kibanaserver
  password: {{ openSearchDashboardPassword }}
  cookie: {{ random_password() }}
