apiVersion: opensearch.stackable.tech/v1alpha1
kind: OpenSearchCluster
metadata:
  name: opensearch
spec:
  image:
    productVersion: {{ opensearchVersion }}
    pullPolicy: IfNotPresent
  nodes:
    roleGroups:
      default:
        config:
          listenerClass: cluster-internal
          resources:
            cpu:
              min: "1"
              max: "2"
            memory:
              limit: "2Gi"
            storage:
              data:
                capacity: 10Gi
        replicas: 1
    configOverrides:
      opensearch.yml:
        # Disable memory mapping; If enabled, the kernel setting vm.max_map_count
        # would need to be increased to 262144 on the node
        node.store.allow_mmap: "false"
        # Disable the disk allocation decider to prevent issues with security index creation
        cluster.routing.allocation.disk.threshold_enabled: "false"
        # Allow automatic initialization of security index
        plugins.security.allow_default_init_securityindex: "true"
    podOverrides:
      spec:
        containers:
          - name: opensearch
            volumeMounts:
              - name: security-config
                mountPath: /stackable/opensearch/config/opensearch-security
                readOnly: true
        volumes:
          - name: security-config
            secret:
              secretName: opensearch-security-config
              defaultMode: 0o660
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-security-config
stringData:
  action_groups.yml: |
    ---
    _meta:
      type: actiongroups
      config_version: 2
  allowlist.yml: |
    ---
    _meta:
      type: allowlist
      config_version: 2

    config:
      enabled: false
  audit.yml: |
    ---
    _meta:
      type: audit
      config_version: 2

    config:
      enabled: false
  config.yml: |
    ---
    _meta:
      type: config
      config_version: 2

    config:
      dynamic:
        authc:
          basic_internal_auth_domain:
            description: Authenticate via HTTP Basic against internal users database
            http_enabled: true
            transport_enabled: true
            order: 1
            http_authenticator:
              type: basic
              challenge: true
            authentication_backend:
              type: intern
        authz: {}
  internal_users.yml: |
    ---
    _meta:
      type: internalusers
      config_version: 2

    admin:
      hash: {{ bcrypt(password=openSearchAdminPassword) }}
      reserved: true
      backend_roles:
        - admin
      description: OpenSearch admin user

    kibanaserver:
      hash: {{ bcrypt(password=openSearchDashboardPassword) }}
      reserved: true
      description: OpenSearch Dashboards user
  nodes_dn.yml: |
    ---
    _meta:
      type: nodesdn
      config_version: 2
  roles.yml: |
    ---
    _meta:
      type: roles
      config_version: 2
  roles_mapping.yml: |
    ---
    _meta:
      type: rolesmapping
      config_version: 2

    all_access:
      reserved: false
      backend_roles:
        - admin

    kibana_server:
      reserved: true
      users:
        - kibanaserver
  tenants.yml: |
    ---
    _meta:
      type: tenants
      config_version: 2
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-user
stringData:
  username: admin
  password: {{ openSearchAdminPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-dashboard-user
stringData:
  username: kibanaserver
  password: {{ openSearchDashboardPassword }}
  cookie: {{ random_password() }}
