apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: keycloak
spec:
  provider:
    oidc:
      hostname: keycloak-gaiax-aas-demo.stackable.tech
      tls:
        verification:
          server:
            caCert:
              webPki: {}
      rootPath: /realms/gaia-x
      scopes: [openid profile email]
      principalClaim: preferred_username
