apiVersion: batch/v1
kind: Job
metadata:
  name: patch-aas-postgres
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      containers:
      - name: postgres-patch
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-aas
              key: postgres-password
        - name: PGUSER
          value: aas
        - name: PGHOST
          value: postgresql-aas
        image: docker.io/bitnami/postgresql:15.3.0-debian-11-r24
        command: ["psql",  "-c", "UPDATE oauth2_registered_client SET redirect_uris=replace(redirect_uris,'http://key-server:8080/','https://keycloak-gaiax-aas-demo.stackable.tech/');"]
      restartPolicy: Never
