---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-regorules
  labels:
    opa.stackable.tech/bundle: true
data:

  verification.rego: |
    package trino

    import rego.v1

    default allow := true

    batch contains index if {
      input.action.operation != "FilterColumns"

      some index, resource in input.action.filterResources
      allow with input.action.resource as resource
    }

   