---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-regorules
  labels:
    opa.stackable.tech/bundle: true
data:

  verification.rego: |
    # METADATA
    # schemas:
    #   - input: schema.input
    #   - data.policies: schema.policies
    package trino

    import rego.v1

    # METADATA
    # description: Comparision of requested and actual permissions
    # entrypoint: true
    default allow := true

   