---
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: nifi
  labels:
    stackable.tech/vendor: Stackable
spec:
  image:
    productVersion: 1.23.2
  clusterConfig:
    authentication:
      - authenticationClass: nifi-admin-credentials
    listenerClass: external-unstable
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
    zookeeperConfigMapName: nifi-znode
  nodes:
    config:
      resources:
        cpu:
          min: "2"
          max: "4"
        memory:
          limit: '6Gi'
        storage:
          contentRepo:
            capacity: "10Gi"
          databaseRepo:
            capacity: "1Gi"
          flowfileRepo:
            capacity: "2Gi"
          provenanceRepo:
            capacity: "4Gi"
          stateRepo:
            capacity: "1Gi"
    roleGroups:
      default:
        replicas: 2
---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: nifi-admin-credentials
  labels:
    stackable.tech/vendor: Stackable
spec:
  provider:
    static:
      userCredentialsSecret:
        name: nifi-admin-credentials-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: nifi-admin-credentials-secret
  labels:
    stackable.tech/vendor: Stackable
stringData:
  admin: {{ nifiAdminPassword }}
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: nifi-znode
  labels:
    stackable.tech/vendor: Stackable
spec:
  clusterRef:
    name: zookeeper
