---
apiVersion: nifi.stackable.tech/v1alpha1
kind: NifiCluster
metadata:
  name: nifi
spec:
  image:
    productVersion: 2.6.0
  clusterConfig:
    authentication:
      - authenticationClass: nifi-admin-credentials
    sensitiveProperties:
      keySecret: nifi-sensitive-property-key
      autoGenerate: true
  nodes:
    roleConfig:
      listenerClass: external-stable
    config:
      resources:
        cpu:
          min: "2"
          max: "4"
        memory:
          limit: "6Gi"
        storage:
          contentRepo:
            capacity: "10Gi"
          databaseRepo:
            capacity: "1Gi"
          flowfileRepo:
            capacity: "2Gi"
          provenanceRepo:
            capacity: "4Gi"
          stateRepo:
            capacity: "1Gi"
    roleGroups:
      default:
        replicas: 2
---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: nifi-admin-credentials
spec:
  provider:
    static:
      userCredentialsSecret:
        name: nifi-admin-credentials-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: nifi-admin-credentials-secret
stringData:
  admin: "{{ nifiAdminPassword }}"
