---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  image:
    productVersion: 3.9.2
    custom: docker.stackable.tech/stackable-experimental/zookeeper:3.9.2-stackable24.3.0
  servers:
    roleGroups:
      default:
        replicas: 3
