---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: zookeeper
spec:
  image:
    custom: docker.stackable.tech/stackable-experimental/zookeeper:3.8.3-stackable23.11.0
    productVersion: 3.8.3
  servers:
    roleGroups:
      default:
        replicas: 3
    podOverrides:
      spec:
        nodeSelector:
          kubernetes.io/arch: arm64
