---
apiVersion: v1
kind: Secret
metadata:
  name: sealed-secrets-key
stringData:
  # Generated on 2025/04/12
  # openssl req -x509 -nodes -newkey rsa:4096 -keyout tls.key -out tls.crt -subj "/CN=sealed-secrets" -days 3650
  # required for sealed secrets decryption
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFEzCCAvugAwIBAgIUFWEYhsQ0cTg6XATOSu70TgA/BGQwDQYJKoZIhvcNAQEL
    BQAwGTEXMBUGA1UEAwwOc2VhbGVkLXNlY3JldHMwHhcNMjUwNDEyMDIxODEyWhcN
    MzUwNDEwMDIxODEyWjAZMRcwFQYDVQQDDA5zZWFsZWQtc2VjcmV0czCCAiIwDQYJ
    KoZIhvcNAQEBBQADggIPADCCAgoCggIBAMbJgXSu4ELhULYyraB4l/fnGHf8NXNM
    z/PG452XrKBGdElOScxYhkentBtGUlfsYeoanOwZikKLr3ngoMzvYIuoLCqkQbA2
    u5jlP8VUtTsMc0amYPAJeEvW/KLbH/6/BFJC9Qrt/kglvVRyDWOb2VN1Dx8RbY0Q
    uWqdF460OGacStyHnRgpp43a7vb4YRKxNkb7Na1s+KYUIa6hJPgIIfLGxksiQKAr
    zuRKFATImFDVzXiXLHP8c7qcQa4+bg9C194CUoWt+hC2SbrGGFEJ9M6c4TzU7/5y
    aE9f4TTZfadH77XpukraI26fDnLKuspK5r3VFmEWE7d8qft6J8i9Dwl9OI7DJfUx
    /dHOFAb/6oiN8TmIRtR6fnreuBv5qWq3B8wnfxmVNf22C0rS8KQaj019IQdZk1Sm
    hOXfTtoZ4vZk9pw+gFdkoNF1rMqzmQnoR+IcKmWRydLx0pftQ3IpGYBqncfNnaK0
    tCag+dZbmPVtL8M5ovWX1WUoAfKSczBaxMnYO3I57R5jEEOR4BfWIdPEVVMgni2u
    tO560gYMHpQHGzkaH8Doa0ZyV64rctEQhCIU4bV6JzwvDnYE8O96ej3n75NIYwKF
    NmSNslExd5DP2fLlIK9mnh5q8FwFqGjqefTVUJ+0pCCMRCvID8FjcqCPEF4Xvpf7
    6LRNSF5gerelAgMBAAGjUzBRMB0GA1UdDgQWBBTuOIW0EZNXykIIvU0L8xhOfU5z
    mzAfBgNVHSMEGDAWgBTuOIW0EZNXykIIvU0L8xhOfU5zmzAPBgNVHRMBAf8EBTAD
    AQH/MA0GCSqGSIb3DQEBCwUAA4ICAQBQlrQ0pfAjUSu44ZWwXpkSxNERwKI1eMUO
    XroKPRSAmdB/tB7JgH3wdT/Yz7pdzvt0LKu1SlcIQXRJ5VsG9k7clhJXQ1Ogse7w
    g7TvQWp49uw8OlVY/mJXlia7dgKiyREGSGjpSsUC+pHcFRmZ4N2los7agY62hZS0
    68esldNIHLPR9PfM84jGfkk1CkFefayROL7kITVemBKHBPw5Jo8JSLnahSmfiJ1e
    K7SY7u/j5PY3MobnjB0MtxaDovmJjjvZ9eQZsTSRnDsHOWZEcHZ1Eoga6NEjaGG2
    kYX8RFp8TM1xhq77/+uTWxhXyekrlxmhBY/ft/C34cm4jM0qw8db8fMXsYtPo/G1
    Cq3ry8+XpqM28TtqHy8hj9nK/WQNvJ9z892FVk7nbBcFzctomdXO9vh+p9C5PW6u
    dkofuMW3EC0HuinXZoUiFMwVSGF6lm7lxgkNnn9JJa7v1OCJVqQxFGoJk2gDh+Ub
    zHCuy/s4nu5MsBX3xJgp2h7/DPAr1DO04tmAUZ9OwpEyeYzWogM2cIm6yeMRNl5+
    xqhWZGh7/5s5iik1g0wB5o08IwKlTMI/b1cNbJBymgjwqGlJRRAKP2IwvFGae3sX
    no3+9FB1FJjEX7sKIHFqN03w1GyrPW4qqc/9is6UaLmxTlu98QeMikel+Wjpd8bP
    DAIkrU/MPw==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQDGyYF0ruBC4VC2
    Mq2geJf35xh3/DVzTM/zxuOdl6ygRnRJTknMWIZHp7QbRlJX7GHqGpzsGYpCi695
    4KDM72CLqCwqpEGwNruY5T/FVLU7DHNGpmDwCXhL1vyi2x/+vwRSQvUK7f5IJb1U
    cg1jm9lTdQ8fEW2NELlqnReOtDhmnErch50YKaeN2u72+GESsTZG+zWtbPimFCGu
    oST4CCHyxsZLIkCgK87kShQEyJhQ1c14lyxz/HO6nEGuPm4PQtfeAlKFrfoQtkm6
    xhhRCfTOnOE81O/+cmhPX+E02X2nR++16bpK2iNunw5yyrrKSua91RZhFhO3fKn7
    eifIvQ8JfTiOwyX1Mf3RzhQG/+qIjfE5iEbUen563rgb+alqtwfMJ38ZlTX9tgtK
    0vCkGo9NfSEHWZNUpoTl307aGeL2ZPacPoBXZKDRdazKs5kJ6EfiHCplkcnS8dKX
    7UNyKRmAap3HzZ2itLQmoPnWW5j1bS/DOaL1l9VlKAHyknMwWsTJ2DtyOe0eYxBD
    keAX1iHTxFVTIJ4trrTuetIGDB6UBxs5Gh/A6GtGcleuK3LREIQiFOG1eic8Lw52
    BPDveno95++TSGMChTZkjbJRMXeQz9ny5SCvZp4eavBcBaho6nn01VCftKQgjEQr
    yA/BY3KgjxBeF76X++i0TUheYHq3pQIDAQABAoICAAi5ieTG6Ha5qxWgF6DyLLYC
    TtTfUoeUZhEnQtC6ejwQ847PG0FB27zpNlK3Iqs+ElXDJBg0Y8OEHCgfgjc/Gg/v
    H5HMjUnbER9GupE3j0+/k2SqWJlYdQ7xE+a1nYvMXaJwUrnPfx2yswKx5yFe0v+i
    ejmCcI+PMxrOjnI35JIpBxvIQ6PD75keiZFN4/wnyn/Ri/DSwP67EKJjQLs2fNT0
    wU8aulboAqfgPMzb8rF453svjrwq0aKDCVqeM1hDS7RbCj0DSTUyvFLbWcW0HT+f
    QOnZrQyQKsCxxDGSCn2NKaR56nBZbtIutCSOKNDIT6R30IhjfsCK0xluP7DuuVTn
    u8jHZ/Lw3WT6YdkCC/XamQ78sz8YbsccvcIGL1IOoh41DsJ71A4De+L6awqj6d2v
    n/YUx+qNrAQPC/qXU5FEb+KUOaHuCL31UjdRCjQSyFmu8OH5Z0IuYClO9c0gW3ej
    QfLcMpASnQft/jbwhmK16SceEpssu7XSFbfSNDCeK+Au7jXXvl3joEr8sqfWTryR
    LYRVEZH1nzpycl2Q6B7Lr8GAj3BEIpmYUiz+5Iz7n/Ocl7m0pLO0rsriL3p5nMcs
    ZN3/J5vrelx+t8NJZ1idg7wUjHpRnFpvTIfdfZactZH1M22jVH2kaMsN78shIr7Z
    NKCEPW3/jZPDQ1Qw58y5AoIBAQDlOsoUWwHbS2ZHCYYZ6Ef8CXpJHYpGnqfu6dEK
    VOavL5HtxrrAhot/DYodATn5LdsU9iI6j+TBRgafgrcyhVSzXdpNDYCeCCroQAyl
    P+p4MeC5YTKnqEOHeCEJ2hXbxL67umjykP5tAGSgNianUKO3MUm6qyJY3mpuotFj
    t4zxstVxjk4xwROzSReN6VvNS8NbGZ5AkIiVaXiHk48jNOY7KwByRHh+RLk2juiK
    UTLeIsVL193kF26WTFKzz+4OImk5OWmIS4bW901qsEeTMk5DEZf+YalFCs/iXjKF
    BjlPkkA4U52lF8ps2RRBl97p5AuypFFFWTL6qu+5K+nkhKUZAoIBAQDeAJXjnbNQ
    BZT4I1JpuUBwTQVkedDMch7aCsnxQ86I7Enu39w+5UKvgW5b4XOGGvzHpqrwNvXa
    tTLjcS5o0ucL2dwAuQ2k31TxC1mHyzPsf9gFBr/qm3ej/qFM+F4qFDH5JpHRMxSR
    LU4jX1Z9jk3IjDvQYgCAcQ9Q63BANoaMwIw8oitiysaM9oRe5NXGBURuegre8xGQ
    mM1867z67vigG9+oWAvOiCYibq8AqS7QH4azP39H0w840SDkxPNpmyfjo/cIkKoQ
    X4h8TbWHSDAWZZYzqLB9pSHfLZXZpvIaJLyqc8UnkvRbrUQuwB3nORlIMB5lc1L0
    TMnDHfb1hUxtAoIBAQC+/TiZtSna2PuifGDq/QndCNiGSsKHDHHHMbEl9o8tr2ja
    wBWhi3h2p4VHnVn8LyS2Vk02leV20y15gaO5yDVGLRBR2soq4Ys+bv8aQCLPel9O
    lZlq71s0Z/a/CqHjtg1kxG/kisIxd35frj6OcTW20K4phaTcfpQXEjl759bbGrGU
    J4knE0OiwWeKqb//UPy3zqR4DvR96J6v91Xvc4fQDIgWrM3oBsJ6np9Jf1XulvHj
    uzv5azyMpZLSlpA13p3lO9yd3q++M9ag6bb5AZULdIE7RYuPJu8GII3fH8xoa+Zu
    B9z1TNkvz7582Fi2b3b/pMDCEwvSptGNavU5nPshAoIBABT5mS/YRojY/iozrCWx
    CxWRMWE84S1v2tpfCpVxAqKNMK8RF44ZuyM552Nm+bNB+YAjjyMDDleLpzM2Dlx5
    ELtd6htnYJKjRzM/D0Z1PIKr0Y0oBhn0dmlYNYVAMiVnoxEXQ8+wM9FDpo5RA6r5
    NwArv7sAh2ubQwcyN3jZrfy+dIGGEPNUlU3cPMV6eXgsJzsI7N4DuTUgOsoCu+g5
    i+QUvhz5tKPe2TuHmaFGWtXvJJrq9OukVVvY5nK26QihUDOB2mVExcymOg8EiJIv
    j9uN3ZMj7QjyATFE7VOTImy1691u8sG6cLv4suh33ltqWakoYrbTHpNWbfmxaxPn
    dEECggEALNKGY0JSHzuwA8wL7XoiOawHJdfBx5BenpM8NpsKAFVACsVZcY4OzJHB
    Dwdr4bhBcRaHrHdM1RrqIvnWnF2gaiNNifNZ9MwHberWhjqQMqdRiv7RD6wp/jPe
    jeIFj/endqSWp3LhyayK8pHZDAEbx57sex0doiosyhCvqYWlcDe2XwvTxGkdpM8J
    V9nqyQh7zNYvVZUby43Gl+Bdbxirolq5Jcx+Z2wxiXt2pL3JArGtnbwHFNP0oZio
    2RmFjD0ZqLQzYmWObQeYKMHcz/8kMNtNhgUax0ZXTGOGEt4bO6Iu2S/V/thVg/Wn
    hnSzVDPZAGg6LcqDPW9csv6W+BCo9w==
    -----END PRIVATE KEY-----
