---
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  image:
    productVersion: 6.0.0
  clusterConfig:
    credentialsSecretName: superset-admin-credentials
    metadataDatabase:
      postgresql:
        host: postgresql-superset
        database: superset
        credentialsSecretName: superset-postgresql-credentials
  nodes:
    roleConfig:
      listenerClass: external-stable
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-admin-credentials
type: Opaque
stringData:
  adminUser.username: admin
  adminUser.firstname: Superset
  adminUser.lastname: Admin
  adminUser.email: admin@superset.com
  adminUser.password: "{{ supersetAdminPassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: superset-postgresql-credentials
stringData:
  username: superset
  password: superset
# ---
# TODO Use when available (https://github.com/stackabletech/superset-operator/issues/3)
# apiVersion: superset.stackable.tech/v1alpha1
# kind: TrinoConnection
# metadata:
#   name: superset-trino-connection
# spec:
#   superset:
#     name: superset
#   trino:
#     name: trino
