---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
  name: minio
spec:
  # Hostname must match secret op's certificate SAN
  host: minio.default.svc.cluster.local
  port: 9000
  accessStyle: Path
  credentials:
    secretClass: minio-s3-credentials
  tls:
    verification:
      server:
        caCert:
          secretClass: tls
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: minio-s3-credentials
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-s3-credentials
  labels:
    secrets.stackable.tech/class: minio-s3-credentials
stringData:
  accessKey: admin
  secretKey: {{ minioAdminPassword }}
