= Demos
:description: Explore Stackable demos showcasing data platform architectures. Includes external components for evaluation.

The pages in this section guide you on how to use the demos provided by Stackable.
To install a demo follow the xref:management:stackablectl:quickstart.adoc[quickstart guide] or have a look at the xref:management:stackablectl:commands/demo.adoc[demo command].
These are the available demos:

include::partial$demos.adoc[]

[IMPORTANT]
.External Components in these demos
====
These demos are provided by Stackable as showcases to demonstrate potential architectures that could be built with the Stackable Data Platform.
As such they may include components that are not supported by Stackable as part of our commercial offering.

If you are evaluating one or more of these demos with the intention of purchasing a subscription, make sure to double-check the list of supported operators; anything that is not mentioned on there is not part of our commercial offering.

Below you can find a list of components that are currently contained in one or more of the demos for reference, if something is missing from this list and also not mentioned on our operators list, then this component is not supported:

* Grafana
* JupyterHub
* MinIO
* OpenLDAP
* OpenSearch
* OpenSearch Dashboards
* PostgreSQL
* Prometheus
* Redis
====

== Demo Code

The manifests and code used by the demos, can be found in the https://github.com/stackabletech/demos[demo repository,window=_blank]. Each demo is constructed in the following way:

* `demos/demos-v2.yaml` file: lists the available demos and uses additional parameters to build up the demo, e.g.
  ** `stackableStack` references the stack belonging to this demo
  ** `manifests` includes a list of additional manifests for the demo, mostly jobs to create tables or ingest example data
  ** `resourceRequests` specifying the needed resources for the demo to run
* `stacks/stacks-v2.yaml` file: lists the available stacks, which are referenced by the `demos/demos-v2.yaml` file, and uses additional parameters to build up the demo, e.g.
  ** `stackableOperators` are all the operators that are installed as part of the demo
  ** `manifests` contains all the manifests needed to setup the products and third-party tools
  ** `parameters` is a list of values used in the manifest files, for example as credentials or other settings
