---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: airflow-events-reader
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-events-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: airflow-serviceaccount
  namespace: default
roleRef:
  kind: Role
  name: airflow-events-reader
  apiGroup: rbac.authorization.k8s.io
