---
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: hbase
spec:
  image:
    productVersion: 2.6.2
  clusterConfig:
    hdfsConfigMapName: hdfs
    zookeeperConfigMapName: hbase-znode
  masters:
    config:
      listenerClass: external-stable
      resources:
        memory:
          limit: 2Gi
    roleGroups:
      default:
        replicas: 1
  regionServers:
    config:
      listenerClass: external-unstable
    roleGroups:
      default:
        replicas: 2
  restServers:
    config:
      listenerClass: external-unstable
    roleGroups:
      default:
        replicas: 1
