---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: zookeeper
  labels:
    stackable.tech/vendor: Stackable
spec:
  image:
    productVersion: 3.8.3
  servers:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: hdfs-znode
  labels:
    stackable.tech/vendor: Stackable
spec:
  clusterRef:
    name: zookeeper
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: hbase-znode
  labels:
    stackable.tech/vendor: Stackable
spec:
  clusterRef:
    name: zookeeper
