---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-serviceaccount
  namespace: default
  labels:
    stackable.tech/vendor: Stackable
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: demo-clusterrolebinding
  labels:
    stackable.tech/vendor: Stackable
subjects:
  - kind: ServiceAccount
    name: demo-serviceaccount
    namespace: default
roleRef:
  kind: ClusterRole
  name: demo-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demo-clusterrole
  labels:
    stackable.tech/vendor: Stackable
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - spark.stackable.tech
    resources:
      - sparkapplications
    verbs:
      - get
      - list
      - watch
      - create
