---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stackable-operators
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - operator: commons
                - operator: listener
                - operator: secret
                - operator: airflow
                - operator: druid
                - operator: hbase
                - operator: hdfs
                - operator: hive
                - operator: kafka
                - operator: nifi
                - operator: opa
                # TODO: enable Opensearch operator
                # - opensearch
                - operator: spark-k8s
                - operator: superset
                - operator: trino
                - operator: zookeeper
          - list:
              elements:
                - cluster: demo
                  server: https://kubernetes.default.svc
                  targetRevision: "{{ stackableReleaseVersion }}"
  # {% raw %}
  template:
    metadata:
      name: "{{ operator }}-operator"
    spec:
      project: stackable-operators
      ignoreDifferences:
        # mitigating: https://github.com/stackabletech/hdfs-operator/issues/626
        - group: "apiextensions.k8s.io"
          kind: "CustomResourceDefinition"
          jqPathExpressions:
            - .spec.names.categories | select(. == [])
            - .spec.names.shortNames | select(. == [])
            - .spec.versions[].additionalPrinterColumns | select(. == [])
      source:
        repoURL: "oci.stackable.tech"
        targetRevision: "{{ targetRevision }}"
        chart: "sdp-charts/{{ operator }}-operator"
        helm:
          releaseName: "{{ operator }}-operator"
      destination:
        server: "{{ server }}"
        namespace: stackable-operators
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        automated:
          selfHeal: true
          prune: true
  # {% endraw %}
