---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  labels:
    stackable.tech/vendor: Stackable
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark
  labels:
    stackable.tech/vendor: Stackable
subjects:
  - kind: ServiceAccount
    name: spark
roleRef:
  kind: Role
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  labels:
    stackable.tech/vendor: Stackable
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [services]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [configmaps]
    verbs: ["*"]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: ["*"]
