---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-hdfs-dir
spec:
  template:
    spec:
      containers:
        - name: create-hdfs-dir
          image: oci.stackable.tech/sdp/hadoop:3.4.0-stackable0.0.0-dev
          # yamllint disable rule:line-length
          command: [
            "bash", "-c", "/stackable/hadoop/bin/hdfs dfs -mkdir -p /gas-sensor-data \
            && /stackable/hadoop/bin/hdfs dfs -chown -R access-spark /gas-sensor-data"
            ]
          # yamllint enable rule:line-length
          volumeMounts:
            - name: hdfs-discovery-configmap
              mountPath: /hdfs
          env:
            - name: HADOOP_CONF_DIR
              value: /hdfs
      volumes:
        - name: hdfs-discovery-configmap
          configMap:
            name: hdfs
      restartPolicy: OnFailure
  backoffLimit: 50
