# klist -kt /stackable/kerberos/keytab
# kinit -kt /stackable/kerberos/keytab nn/hdfs.default.svc.cluster.local@KNAB.COM
# cat > /tmp/test.py
# bin/hdfs dfs -put /tmp/test.py /lakehouse/test.py
# cat > /tmp/banner.py
# bin/hdfs dfs -put /tmp/banner.py /lakehouse/banner.py
---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkApplication
metadata:
  name: test-pyspark-from-hdfs
spec:
  sparkImage:
    productVersion: 3.5.1
  mode: cluster
  mainApplicationFile: hdfs:/lakehouse/test.py # Using this folder, as my user only has permissions for that folder (e2e-security demo)
  deps:
    packages:
      - org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.0
  sparkConf:
    ### SUT
    spark.submit.pyFiles: hdfs:/lakehouse/banner.py
    ### END SUT
    spark.driver.extraClassPath: /stackable/config/hdfs
    spark.executor.extraClassPath: /stackable/config/hdfs
    spark.hadoop.hive.metastore.kerberos.principal: hive/hive-iceberg.default.svc.cluster.local@KNAB.COM
    spark.hadoop.hive.metastore.sasl.enabled: "true"
    spark.kerberos.keytab: /stackable/kerberos/keytab
    spark.kerberos.principal: spark/spark.default.svc.cluster.local@KNAB.COM
    spark.sql.catalog.lakehouse: org.apache.iceberg.spark.SparkCatalog
    spark.sql.catalog.lakehouse.type: hive
    spark.sql.catalog.lakehouse.uri: thrift://hive-iceberg:9083
    spark.sql.defaultCatalog: lakehouse
    spark.sql.extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
  job:
    config:
      volumeMounts: &volumeMounts
        - name: script
          mountPath: /stackable/spark/jobs
        - name: hdfs-config
          mountPath: /stackable/config/hdfs
        - name: kerberos
          mountPath: /stackable/kerberos
        # Yes, I'm too lazy to fiddle around with JVM arguments... (-Djava.security.krb5.conf=/example/path/krb5.conf)
        - name: kerberos
          mountPath: /etc/krb5.conf
          subPath: krb5.conf
    envOverrides: &envOverrides
      KERBEROS_REALM: KNAB.COM
      HADOOP_CONF_DIR: /stackable/config/hdfs
    # As the envOverrides are not working
    podOverrides:
      spec:
        containers:
          - name: spark-submit
            env:
              - name: KERBEROS_REALM
                value: KNAB.COM
              - name: HADOOP_CONF_DIR
                value: /stackable/config/hdfs
  driver:
    config:
      volumeMounts: *volumeMounts
      resources: # I would like to run this stack on my Laptop
        cpu:
          min: 100m
    envOverrides: *envOverrides
    podOverrides: &podOverrides
      spec:
        containers:
          - name: spark
            # As the envOverrides are not working
            env:
              - name: KERBEROS_REALM
                value: KNAB.COM
              - name: HADOOP_CONF_DIR
                value: /stackable/config/hdfs
  executor:
    replicas: 1
    config:
      volumeMounts: *volumeMounts
      resources: # I would like to run this stack on my Laptop
        cpu:
          min: 250m
    envOverrides: *envOverrides
    podOverrides: *podOverrides
  volumes:
    - name: script
      configMap:
        name: spark-report-script
    - name: hdfs-config
      configMap:
        name: hdfs
    - name: kerberos
      ephemeral:
        volumeClaimTemplate:
          metadata:
            annotations:
              secrets.stackable.tech/class: kerberos
              secrets.stackable.tech/kerberos.service.names: spark
              secrets.stackable.tech/scope: service=spark
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: "1"
            storageClassName: secrets.stackable.tech
