---
apiVersion: batch/v1
kind: Job
metadata:
  name: create-tables-in-trino
spec:
  template:
    spec:
      serviceAccountName: demo-serviceaccount
      containers:
        - name: create-tables-in-trino
          image: oci.stackable.tech/sdp/testing-tools:0.3.0-stackable0.0.0-dev
          command: ["bash", "-c", "python -u /tmp/script/script.py"]
          volumeMounts:
            - name: script
              mountPath: /tmp/script
            - name: trino-users
              mountPath: /trino-users
      volumes:
        - name: script
          configMap:
            name: create-tables-in-trino-script
        - name: trino-users
          secret:
            secretName: trino-users
      restartPolicy: OnFailure
  backoffLimit: 50
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: create-tables-in-trino-script
data:
  script.py: |
    import sys
    import trino

    if not sys.warnoptions:
        import warnings
    warnings.simplefilter("ignore")

    def get_connection():
        connection = trino.dbapi.connect(
            host="trino-coordinator",
            port=8443,
            user="admin",
            http_scheme='https',
            auth=trino.auth.BasicAuthentication("admin", open("/trino-users/admin").read()),
        )
        connection._http_session.verify = False
        return connection

    def run_query(connection, query):
        print(f"[DEBUG] Executing query {query}")
        cursor = connection.cursor()
        cursor.execute(query)
        return cursor.fetchall()

    connection = get_connection()

    run_query(connection, "CREATE SCHEMA iceberg.dbt_schema WITH (location = 's3a://demo/dbt_schema')")
