additionalLabels:
  stackable.tech/vendor: Stackable
podLabels:
  stackable.tech/vendor: Stackable
rootUser: admin
rootPassword: adminadmin
mode: distributed
replicas: 5
persistence:
  size: 250Gi
buckets:
  - name: staging
    policy: public
  - name: lakehouse
    policy: public
resources:
  requests:
    cpu: 500m
    memory: 2Gi
service:
  type: NodePort
  nodePort: null
consoleService:
  type: NodePort
  nodePort: null
tls:
  enabled: true
extraVolumes:
  # Request a TLS certificate from the secret-operator
  - name: tls
    ephemeral:
      volumeClaimTemplate:
        metadata:
          annotations:
            secrets.stackable.tech/class: tls
            secrets.stackable.tech/scope: |-
              service=minio,pod
        spec:
          storageClassName: secrets.stackable.tech
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1
  # Create an in-memory emptyDir to copy the certs to (to avoid permission errors)
  - name: certs
    emptyDir:
      sizeLimit: 5Mi
      medium: Memory
extraVolumeMounts:
  # Mount the certificate generated by the secret-operator
  - name: minio-tls
    mountPath: /etc/minio/original_certs
  # On startup, we will rename the certs and move them here:
  - mountPath: /etc/minio/certs
    name: certs
customCommandJob:
  extraVolumes:
    # Request a TLS certificate from the secret-operator
    - name: minio-tls
      ephemeral:
        volumeClaimTemplate:
          metadata:
            annotations:
              secrets.stackable.tech/class: tls
              secrets.stackable.tech/scope: |-
                service=minio,pod
          spec:
            storageClassName: secrets.stackable.tech
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1
    # Create an in-memory emptyDir to copy the certs to (to avoid permission errors)
    - name: certs
      emptyDir:
        sizeLimit: 5Mi
        medium: Memory
  # WARNING: this is currently only used by the custom-scripts job container. Other containers do not mount these.
  extraVolumeMounts:
    # Mount the certificate generated by the secret-operator
    - name: minio-tls
      mountPath: /etc/minio/mc/original_certs
    # On startup, we will rename the certs and move them here:
    - mountPath: /etc/minio/mc/certs/CAs
      name: certs
