---
name: Build and publish jupyter-pyspark-with-alibi-detect

on:
  workflow_dispatch:
  push:
    branches:
      - main
      # TODO (@NickLarsenNZ): Also build on release branches, but with a stackable0.0.0-dev or stackableXX.X.X tag.
      # - release-*
    paths:
      - demos/signal-processing/Dockerfile-jupyter
      - demos/signal-processing/requirements.txt
      - .github/workflows/dev_jupyter-pyspark-with-alibi-detect.yaml

jobs:
  build_image:
    name: Reusable Workflow
    uses: ./.github/workflows/reusable_build_image.yaml
    secrets:
      harbor-robot-secret: ${{ secrets.HARBOR_ROBOT_DEMOS_GITHUB_ACTION_BUILD_SECRET }}
    with:
      image-name: jupyter-pyspark-with-alibi-detect
      # TODO (@NickLarsenNZ): Use a versioned image with stackable0.0.0-dev or stackableXX.X.X so that
      # the demo is reproducable for the release and it will be automatically replaced for the release branch.
      image-version: python-3.9
      containerfile-path: demos/signal-processing/Dockerfile-jupyter
