---
on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-version:
        required: true
        type: string
      containerfile-path:
        required: true
        type: string
    secrets:
      harbor-robot-secret:
        description: The secret for the Harbor robot user used to push images and manifest
        required: true
      slack-token:
        description: The Slack token used to post failure notifications
        required: true

permissions: {}

jobs:
  build:
    name: Build/Publish ${{ inputs.image-version }}-${{ matrix.runner.arch }} Image
    permissions:
      contents: read
      id-token: write # Needed for cosign keyless signing in publish-image
    runs-on: ${{ matrix.runner.name }}
    strategy:
      matrix:
        runner:
          - { name: "ubuntu-latest", arch: "amd64" }
          - { name: "ubicloud-standard-8-arm", arch: "arm64" }
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Build image
        id: build
        env:
          CONTAINERFILE_PATH: ${{ inputs.containerfile-path }}
          IMAGE_VERSION: ${{ inputs.image-version }}
          IMAGE_NAME: ${{ inputs.image-name }}
        uses: stackabletech/actions/build-container-image@e8aed001d347bcf693e41b61f4098b0cb94b4ab6 # v0.18.0
        with:
          image-name: ${{ env.IMAGE_NAME }}
          image-index-manifest-tag: ${{ env.IMAGE_VERSION }}
          container-file: ${{ env.CONTAINERFILE_PATH }}

      - name: Publish Container Image on oci.stackable.tech
        env:
          IMAGE_NAME: ${{ inputs.image-name }}
        uses: stackabletech/actions/publish-image@e8aed001d347bcf693e41b61f4098b0cb94b4ab6 # v0.18.0
        with:
          image-registry-uri: oci.stackable.tech
          image-registry-username: robot$demos+github-action-build
          image-registry-password: ${{ secrets.harbor-robot-secret }}
          image-repository: demos/${{ env.IMAGE_NAME }}
          image-manifest-tag: ${{ steps.build.outputs.image-manifest-tag }}
          canonical-image-manifest-tag: ${{ steps.build.outputs.image-manifest-tag }}
          canonical-source-image-uri: ${{ steps.build.outputs.image-manifest-uri }}

  publish_manifests:
    name: Build/Publish Manifest
    needs: [build]
    permissions:
      contents: read
      id-token: write # Needed for cosign keyless signing in publish-image-index-manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Publish and Sign Image Index Manifest to oci.stackable.tech
        env:
          IMAGE_VERSION: ${{ inputs.image-version }}
          IMAGE_NAME: ${{ inputs.image-name }}
        uses: stackabletech/actions/publish-image-index-manifest@e8aed001d347bcf693e41b61f4098b0cb94b4ab6 # v0.18.0
        with:
          image-registry-uri: oci.stackable.tech
          image-registry-username: robot$demos+github-action-build
          image-registry-password: ${{ secrets.harbor-robot-secret }}
          image-repository: demos/${{ env.IMAGE_NAME }}
          canonical-image-index-manifest-tag: ${{ env.IMAGE_VERSION }}

  notify:
    name: Failure Notification
    needs: [build, publish_manifests]
    runs-on: ubuntu-latest
    if: failure() || (github.run_attempt > 1 && !cancelled())
    steps:
      - uses: stackabletech/actions/send-slack-notification@e8aed001d347bcf693e41b61f4098b0cb94b4ab6 # v0.18.0
        with:
          publish-manifests-result: ${{ needs.publish_manifests.result }}
          build-result: ${{ needs.build.result }}
          slack-token: ${{ secrets.slack-token }}
          type: container-image-build
          channel-id: "C07UG6JH44F" # notifications-container-images
