{
 "title": "Metric collection overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "product",
    "query": "airflow,druid,hbase,hdfs,hive,kafka,nifi,opensearch,spark-k8s,superset,trino,zookeeper,opa"
   }
  ]
 },
 "panels": [
  { "title": "Stacklets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "${product}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "repeat": "product",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (app_kubernetes_io_instance) ({app_kubernetes_io_name=\"${product}\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "${product}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "repeat": "product",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod) ({app_kubernetes_io_name=\"${product}\",pod!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "Trino",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(trino_memory_clustermemorypool_nodes, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(trino_memory_clustermemorypool_nodes{namespace=~\"$namespace\"},app_kubernetes_io_instance)"
    }
   },
   { "name": "product", "query": "trino" }
  ]
 },
 "panels": [
  {
   "title": "CPU request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster name",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "options": {
    "content": "<center><p style=\"font-size:20px\">$cluster</p></center>"
   }
  },
  {
   "title": "Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_memory_clustermemorypool_nodes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"} - 1 # Subtract 1 for coordinator",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_limits{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_requests{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(container_memory_working_set_bytes{container!=\"\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_requests{resource=\"memory\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(rate(container_network_receive_bytes_total[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))*8",
     "legendFormat": "rx"
    },
    {
     "expr": "-sum(max by (namespace, pod)(rate(container_network_transmit_bytes_total[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))*8",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Running queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (namespace, job) (trino_execution_querymanager_runningqueries{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum by (namespace, job) (trino_execution_querymanager_queuedqueries{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "queued"
    }
   ]
  },
  {
   "title": "Finished queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (namespace, job) (trino_execution_querymanager_completedqueries_totalcount{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "completed"
    },
    {
     "expr": "sum by (namespace, job) (trino_execution_querymanager_failedqueries_totalcount{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum by (namespace, job) (trino_execution_querymanager_abandonedqueries_totalcount{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "abandoned"
    },
    {
     "expr": "sum by (namespace, job) (trino_execution_querymanager_canceledqueries_totalcount{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "canceled"
    }
   ]
  },
  {
   "title": "Internal memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "trino_memory_clustermemorymanager_clustertotalmemoryreservation{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}",
     "legendFormat": "used"
    },
    {
     "expr": "trino_memory_clustermemorymanager_clustermemorybytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Rows/s read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(trino_execution_querymanager_consumedinputrows_totalcount{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Logical bytes read",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(trino_execution_querymanager_consumedinputbytes_totalcount{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval])*8",
     "legendFormat": "read"
    }
   ]
  }
 ]
}
{
 "title": "Kafka",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "product", "query": "kafka" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate, namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_brokerstate{namespace=~\"$namespace\"},app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster name",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "options": {
    "content": "<center><p style=\"font-size:20px\">$cluster</p></center>"
   }
  },
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(kafka_controller_kafkacontroller_activebrokercount{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (topic) (kafka_server_brokertopicmetrics_messagesin_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",topic!=\"\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_limits{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_requests{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(container_memory_working_set_bytes{container!=\"\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_requests{resource=\"memory\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(rate(container_network_receive_bytes_total[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))*8",
     "legendFormat": "rx"
    },
    {
     "expr": "-sum(max by (namespace, pod)(rate(container_network_transmit_bytes_total[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))*8",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Messages / topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(topic)(rate(kafka_server_brokertopicmetrics_messagesin_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",topic!=\"\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes / topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum by(topic)(rate(kafka_server_brokertopicmetrics_bytesin_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",topic!=\"\"}[$__rate_interval]))*8",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Log size / topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(topic)(kafka_log_log_size{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\",topic!=\"\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "PVC usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, persistentvolumeclaim)(kubelet_volume_stats_used_bytes) * on (namespace, persistentvolumeclaim) group_left() (max by (namespace, persistentvolumeclaim) (kube_persistentvolumeclaim_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, persistentvolumeclaim)(kubelet_volume_stats_capacity_bytes) * on (namespace, persistentvolumeclaim) group_left() (max by (namespace, persistentvolumeclaim) (kube_persistentvolumeclaim_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_kafkaserver_linux_disk_read_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval]))*8",
     "legendFormat": "rx"
    },
    {
     "expr": "-sum(rate(kafka_server_kafkaserver_linux_disk_write_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval]))*8",
     "legendFormat": "tx"
    }
   ]
  }
 ]
}
{
 "title": "MinIO",
 "description": "MinIO Grafana Dashboard - https://min.io/",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total S3 Ingress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_received_bytes{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\"$scrape_jobs\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}) by (instance)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_total_bytes{job=~\"$scrape_jobs\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_objects_size_distribution{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Open FDs ",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Total S3 Egress",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_sent_bytes{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "targets": [
    {
     "expr": "minio_node_go_routine_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Cluster Health Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_status{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool: {{pool}} Set: {{set}}"
    }
   ]
  },
  {
   "title": "Total Online/Offline Drives",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_drive_online_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "."
    },
    {
     "expr": "max(minio_cluster_drive_offline_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_bucket_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "S3 API Ingress Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_received_bytes{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Received [{{server}}]"
    }
   ]
  },
  {
   "title": "S3 API Egress Rate ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_s3_traffic_sent_bytes{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "Data Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_nodes_online_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_object_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Time Since Last Heal",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_heal_time_last_activity_nano_seconds{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Time Since Last Scan",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_usage_last_activity_nano_seconds{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "S3 API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_4xx_errors_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server,api) (increase(minio_s3_requests_5xx_errors_total{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server,api}}"
    }
   ]
  },
  {
   "title": "Health Breakdown",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_erasure_set_online_drives{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Online Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_read_quorum{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Read Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_write_quorum{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Write Quorum"
    },
    {
     "expr": "minio_cluster_health_erasure_set_healing_drives{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Healing Drives"
    },
    {
     "expr": "minio_cluster_health_erasure_set_status{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool {{pool}} / Set {{set}} - Status"
    }
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Read, Write I/O",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_node_io_rchar_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node RChar [{{server}}]"
    },
    {
     "expr": "rate(minio_node_io_wchar_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Node WChar [{{server}}]"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(minio_node_process_cpu_total_seconds{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Internode Traffic",
   "type": "timeseries",
   "description": "Total number of bytes received and sent on MinIO cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(minio_inter_node_traffic_sent_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Received [{{server}}]"
    },
    {
     "expr": "rate(minio_inter_node_traffic_received_bytes{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Internode Bytes Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "Open FDs [{{server}}]"
    }
   ]
  },
  {
   "title": "Syscalls",
   "type": "timeseries",
   "description": "Number of online drives per MinIO Server",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minio_node_syscall_read_total{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Read Syscalls [{{server}}]"
    },
    {
     "expr": "rate(minio_node_syscall_write_total{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "Write Syscalls [{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Objects",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_objects_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_versions_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Directories",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_directories_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "KMS Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minio_cluster_kms_uptime{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "KMS Request 4xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_cluster_kms_request_error{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "KMS Online(1)/Offline(0)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "sum by (server) (minio_cluster_kms_online{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Bucket Scans Finished",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_finished{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "KMS Request 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (increase(minio_cluster_kms_request_failure{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "KMS Request Success Rate ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (server) (rate(minio_cluster_kms_request_success{job=~\"$scrape_jobs\"}[$__rate_interval]))",
     "legendFormat": "KMS Request Success [{{server}}]"
    }
   ]
  },
  {
   "title": "Bucket Scans Started",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_started{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  }
 ]
}
{
 "title": "HDFS",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "product", "query": "hdfs" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(fs_namesystem_blocks_total,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(fs_namesystem_blocks_total{namespace=~\"$namespace\"},app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster name",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "options": {
    "content": "<center><p style=\"font-size:20px\">$cluster</p></center>"
   }
  },
  {
   "title": "Journalnodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(journal_node_bytes_written{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namenodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(name_node_name_node_state{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datanodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(datanode_data_node_packet_responder_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_limits{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_requests{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(container_memory_working_set_bytes{container!=\"\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_requests{resource=\"memory\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(rate(container_network_receive_bytes_total[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))*8",
     "legendFormat": "rx"
    },
    {
     "expr": "-sum(max by (namespace, pod)(rate(container_network_transmit_bytes_total[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))*8",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "DFS usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(fs_namesystem_capacity_remaining{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "remaining"
    },
    {
     "expr": "max(fs_namesystem_capacity_used{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "DFS capacity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(fs_namesystem_capacity_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HDFS cluster I/O",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(max by(pod)(rate(datanode_bytes_read{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval])))*8",
     "legendFormat": "rx"
    },
    {
     "expr": "-sum(max by(pod)(rate(datanode_bytes_written{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval])))*8",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Files",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "max(fs_namesystem_files_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "total"
    },
    {
     "expr": "max(fs_namesystem_num_files_under_construction{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "under construction"
    }
   ]
  },
  {
   "title": "DFS used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(fs_namesystem_capacity_used{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DFS remaining",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(fs_namesystem_capacity_remaining{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 17 },
   "targets": [
    {
     "expr": "max(fs_namesystem_blocks_total{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "total"
    },
    {
     "expr": "max(fs_namesystem_missing_blocks{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "missing"
    },
    {
     "expr": "max(fs_namesystem_corrupt_blocks{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "corrupt"
    },
    {
     "expr": "max(fs_namesystem_under_replicated_blocks{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "underreplicated"
    },
    {
     "expr": "max(fs_namesystem_excess_blocks{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "excess"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max(fs_namesystem_total_load{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, persistentvolumeclaim)(kubelet_volume_stats_used_bytes) * on (namespace, persistentvolumeclaim) group_left() (max by (namespace, persistentvolumeclaim) (kube_persistentvolumeclaim_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, persistentvolumeclaim)(kubelet_volume_stats_capacity_bytes) * on (namespace, persistentvolumeclaim) group_left() (max by (namespace, persistentvolumeclaim) (kube_persistentvolumeclaim_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}
{
 "title": "HBase",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "product", "query": "hbase" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(tables_num_tables,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(tables_num_tables{namespace=~\"$namespace\"},app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Masters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(procedure_num_master_wa_ls{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region servers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(server_num_region_servers{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Regions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(server_region_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster name",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "options": {
    "content": "<center><p style=\"font-size:20px\">$cluster</p></center>"
   }
  },
  {
   "title": "Regions in transition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(assignment_manager_rit_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oldest regions in transition",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max by (pod)(assignment_manager_rit_oldest_age{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_limits{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_requests{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(container_memory_working_set_bytes{container!=\"\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_requests{resource=\"memory\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(rate(container_network_receive_bytes_total[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))*8",
     "legendFormat": "rx"
    },
    {
     "expr": "-sum(max by (namespace, pod)(rate(container_network_transmit_bytes_total[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))*8",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Active handlers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(max by (pod)(master_num_active_handler{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}))",
     "legendFormat": "active handlers"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(max by(pod)(rate(server_read_request_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval])))*8",
     "legendFormat": "read"
    },
    {
     "expr": "-sum(max by(pod)(rate(server_write_request_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval])))*8",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Slow operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(max by (pod)(rate(server_slow_get_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "get"
    },
    {
     "expr": "sum(max by (pod)(rate(server_slow_put_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "put"
    },
    {
     "expr": "sum(max by (pod)(rate(server_slow_append_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "append"
    },
    {
     "expr": "sum(max by (pod)(rate(server_slow_delete_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(max by (pod)(rate(server_slow_increment_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}[$__rate_interval])))",
     "legendFormat": "increment"
    }
   ]
  },
  {
   "title": "Regions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(max by (pod)(assignment_manager_rit_count{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}))",
     "legendFormat": "In transition"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Compaction queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max by (pod)(server_compaction_queue_length{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Flush queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "expr": "max by (pod)(server_flush_queue_length{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Split queue length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "max by (pod)(server_split_queue_length{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}
{
 "title": "NiFi",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "product", "query": "nifi" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nifi_amount_bytes_read,namespace)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(nifi_amount_bytes_read{namespace=~\"$namespace\"},app_kubernetes_io_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster name",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "options": {
    "content": "<center><p style=\"font-size:20px\">$cluster</p></center>"
   }
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (pod)(nifi_amount_bytes_read{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(rate(container_cpu_usage_seconds_total{container!=\"\"}[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_limits{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_requests{resource=\"cpu\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(container_memory_working_set_bytes{container!=\"\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, pod)(kube_pod_container_resource_requests{resource=\"memory\"} * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod)(rate(container_network_receive_bytes_total[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))*8",
     "legendFormat": "rx"
    },
    {
     "expr": "-sum(max by (namespace, pod)(rate(container_network_transmit_bytes_total[$__rate_interval]) * on (namespace, pod) group_left() (max by (namespace, pod) (kube_pod_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"}))))*8",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Active threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(pod)(nifi_amount_threads_active{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM heap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(pod)(nifi_jvm_heap_usage{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Amount of bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(nifi_amount_bytes_read{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(nifi_amount_bytes_written{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "written"
    },
    {
     "expr": "sum(nifi_amount_bytes_received{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum(nifi_amount_bytes_sent{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(nifi_amount_bytes_transferred{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "transferred"
    }
   ]
  },
  {
   "title": "Items",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nifi_amount_items_input{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "input"
    },
    {
     "expr": "sum(nifi_amount_items_output{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "output"
    },
    {
     "expr": "sum(nifi_amount_items_queued{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "queued"
    }
   ]
  },
  {
   "title": "Used repository space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(nifi_content_repo_used_space_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "content"
    },
    {
     "expr": "max(nifi_flow_file_repo_used_space_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "flow file"
    },
    {
     "expr": "max(nifi_provenance_repo_used_space_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "provenance"
    }
   ]
  },
  {
   "title": "Free repository space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(nifi_content_repo_free_space_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "content"
    },
    {
     "expr": "max(nifi_flow_file_repo_free_space_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "flow file"
    },
    {
     "expr": "max(nifi_provenance_repo_free_space_bytes{namespace=~\"$namespace\",app_kubernetes_io_instance=~\"$cluster\"})",
     "legendFormat": "provenance"
    }
   ]
  },
  {
   "title": "PVC usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, persistentvolumeclaim)(kubelet_volume_stats_used_bytes) * on (namespace, persistentvolumeclaim) group_left() (max by (namespace, persistentvolumeclaim) (kube_persistentvolumeclaim_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "used"
    },
    {
     "expr": "sum(max by (namespace, persistentvolumeclaim)(kubelet_volume_stats_capacity_bytes) * on (namespace, persistentvolumeclaim) group_left() (max by (namespace, persistentvolumeclaim) (kube_persistentvolumeclaim_labels{namespace=~\"$namespace\",label_app_kubernetes_io_name=~\"$product\",label_app_kubernetes_io_component=~\".*\",label_app_kubernetes_io_instance=~\"$cluster\"})))",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}